#!/usr/bin/env bash

updater-brew-cask-name() {
  echo 'Brew Cask'
}

updater-brew-cask-detect() {
  brew cask > /dev/null 2>&1
}

updater-brew-cask-update() {
  brew update
  brew cask upgrade
}

updater-brew-cask-list() {
  if [ "$1" != '--no-fetch' ]; then
    brew update > /dev/null
  fi

  brew cask outdated
}
