#!/usr/bin/env bash

EMACS_PATH="$HOME/.emacs.d"
EMACS_BIN_PATH="/Applications/Emacs.app/Contents/MacOS/Emacs"

LISP_TO_UPDATE=$(cat <<- LISP
  (progn
    (defadvice prelude-update (around stfu compile activate)
      (flet ((yes-or-no-p (&rest args) t)
             (y-or-n-p (&rest args) t))
       ad-do-it))
    (prelude-update)
    (kill-emacs))
LISP
)

updater-emacs-prelude-name() {
  echo 'Emacs Prelude'
}

updater-emacs-prelude-detect() {
  [ -e "$EMACS_PATH/prelude-modules.el" ]
}

updater-emacs-prelude-update() {
  echo "$LISP_TO_UPDATE"
  $EMACS_BIN_PATH --eval "$LISP_TO_UPDATE"
}

updater-emacs-prelude-list() {
  cd "$EMACS_PATH" || exit

  if [ "$(updater-emacs-prelude-git-incomming | wc -l)" -gt 0 ]; then
    echo Needs update
  fi
}

updater-emacs-prelude-git-incomming() {
  git fetch > /dev/null 2>&1 && git log ..origin/master
}
