#!/usr/bin/env bash

set -e

main() {
  case "$1" in
    count | list | update)
    ;;
    help)
      help
      exit 0
    ;;
    *)
      echo "ERROR: unknown command \"$1\""
      help
      exit 1
      ;;
  esac

  if [ "$2" == '--no-fetch' ] || [ "$3" == '--no-fetch' ]; then
    no_fetch='--no-fetch'
  fi

  if [ "$2" != '--no-fetch' ] && [ ! -z "$2" ]; then
    updater_to_use="updater-$2"
  fi

  updaters | while read -r updater; do
    # shellcheck source=/dev/null
    source "$updater"

    updater_handle="$(basename "$updater")"

    if "$updater_handle-detect" &&
        ([ "$updater_handle" == "$updater_to_use" ] ||
         [ -z "$updater_to_use" ]) ; then
      echo "$("$updater_handle-name"):"

      case "$1" in
        count)
          "$updater_handle-list" "$no_fetch" | wc -l | sed -e 's/^[ \t]*//'
          ;;
        list)
          "$updater_handle-list" "$no_fetch"
          ;;
        update)
          "$updater_handle-update"
          ;;
      esac
      echo ""
    fi
  done
}

help() {
 cat << EOF
Usage:
  updater update [updater]
  updater list [updater] [--no-fetch]
  updater count [updater] [--no-fetch]

Commands:
  update   Update everything
  list     List available updates
  count    Count available updates

Options:
  [updater]    Updater you want to use for command, i.e. brew
  --no-fetch   Try not to fetch info about new updates, and show the result of
               the previous command run without this argument
EOF
}

updaters() {
  if [ -z "$UPDATER_PATH" ]; then
    UPDATER_PATH=$(updaters-defult-path)
  fi
  find "$UPDATER_PATH" -iname "updater-*"
}

updaters-defult-path() {
  echo "$( cd "$(dirname "$0")"; pwd -P )/updater.d"
}


main "$@"
